# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quote_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='Quote_exam.User'),
        ),
    ]
